app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/lldap/lldap
            tag: v0.5.0
          env:
            TZ: Asia/Ho_Chi_Minh
            LLDAP_HTTP_PORT: &httpPort 80
            LLDAP_HTTP_URL: https://lldap.khuedoan.com
            LLDAP_LDAP_PORT: &ldapPort 389
            LLDAP_LDAP_BASE_DN: dc=home,dc=arpa
            LLDAP_JWT_SECRET: REPLACE_WITH_RANDOM # TODO
            LLDAP_LDAP_USER_PASS: REPLACE_WITH_PASSWORD # TODO
          # TODO
          # envFrom:
          #   - secretRef:
          #       name: lldap-secret
  service:
    main:
      ports:
        http:
          port: *httpPort
        ldap:
          port: *ldapPort
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host ldap.khuedoan.com
          paths:
            - path: /
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: lldap-tls-certificate
  persistence:
    data:
      type: emptyDir
