- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Enable EPEL repository
  yum:
    name: epel-release
    state: present

- name: Install snap
  yum:
    name: snapd
    state: present

- name: Enable snapd
  service:
    name: snapd
    enabled: yes
    state: started

- name: Enable classic snap support
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

