apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: cloudflared
  source:
    repoURL: https://khuedoan.github.io/charts
    chart: cloudflared
    targetRevision: 0.1.1
    helm:
      parameters:
        - name: replicaCount
          value: '3'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
