apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: kube-system
    server: ''
  source:
    path: ''
    repoURL: 'https://kubernetes-sigs.github.io/descheduler/'
    targetRevision: 0.20.0
    chart: descheduler
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
