apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-runner-kube
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: drone
  source:
    repoURL: https://charts.drone.io
    chart: drone-runner-kube
    targetRevision: 0.1.5
    helm:
      parameters:
        - name: 'rbac.buildNamespaces[0]'
          value: drone
        - name: env.DRONE_NAMESPACE_DEFAULT
          value: drone
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
