apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  destination:
    name: in-cluster
    namespace: longhorn-system
    server: ''
  source:
    path: ''
    repoURL: 'https://charts.longhorn.io'
    targetRevision: 1.1.0
    chart: longhorn
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
