kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
      - grafana.khuedoan.com
      tls:
      - secretName: grafana-general-tls
        hosts:
        - grafana.khuedoan.com
    additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.loki:3100
