- name: Create etcd container
  docker_container:
    name: etcd-tfstate
    image: bitnami/etcd
    env:
      ALLOW_NONE_AUTHENTICATION: "yes"
    published_ports:
      - 2379:2379
    volumes:
      - /bitnami/etcd/data
