version: '3'

services:
  nginx:
    container_name: "khuedoan_nginx"
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
  index:
    container_name: "khuedoan_index"
    build: ./index/
  gitea:
    container_name: "khuedoan_gitea"
    build: ./gitea/
  mariadb:
    container_name: "khuedoan_mariadb"
    build: ./mariadb/
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
