version: '3'

services:
  nginx:
    container_name: "khuedoan_nginx"
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
  index:
    container_name: "khuedoan_index"
    build: ./index/
  gitea:
    container_name: "khuedoan_gitea"
    build: ./gitea/
    environment:
      DB_TYPE: "mysql"
      DB_HOST: "mariadb:3306"
      DB_USER: "root"
      DB_PASSWD: $MYSQL_ROOT_PASSWORD
      DB_NAME: "gitea"
      APP_NAME: "Git"
      DOMAIN: "git.khuedoan.com"
      ROOT_URL: "http://git.khuedoan.com/"
      INSTALL_LOCK: "true"
  mariadb:
    container_name: "khuedoan_mariadb"
    build: ./mariadb/
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: "gitea"
