version: '3'

services:
  nginx:
    container_name: "khuedoan_nginx"
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
  homepage:
    container_name: "khuedoan_homepage"
    build: ./homepage/
    ports:
      - "8000:8000"
  git:
    container_name: "khuedoan_git"
    build: ./git/
    ports:
      - "3000:3000"
      - "22:22"
  mariadb:
    container_name: "khuedoan_mariadb"
    build: ./mariadb/
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
