app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/jellyfin/jellyfin
            tag: 10.8.13
        transmission:
          image:
            repository: lscr.io/linuxserver/transmission
            tag: 4.0.5
        jackett:
          image:
            repository: lscr.io/linuxserver/jackett
            tag: 0.21.1556
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: 5.2.6
        jellyseerr:
          image:
            repository: docker.io/fallenbagel/jellyseerr
            tag: 1.7.0
  service:
    main:
      ports:
        http:
          port: 8096
          protocol: HTTP
        transmission:
          port: 9091
          protocol: HTTP
        jackett:
          port: 9117
          protocol: HTTP
        radarr:
          port: 7878
          protocol: HTTP
        jellyseerr:
          port: 5055
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &jellyfinHost jellyfin.khuedoan.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
        - host: &transmissionHost transmission.khuedoan.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: transmission
        - host: &jackettHost jackett.khuedoan.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: jackett
        - host: &radarrHost radarr.khuedoan.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: radarr
        - host: &jellyseerrHost jellyseerr.khuedoan.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: jellyseerr
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *jellyfinHost
            - *transmissionHost
            - *jackettHost
            - *radarrHost
            - *jellyseerrHost
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 20Gi
      advancedMounts:
        main:
          main:
            - path: /config
              subPath: jellyfin/config
            - path: /media/movies
              subPath: movies
          transmission:
            - path: /config
              subPath: transmission/config
            - path: /downloads
              subPath: transmission/downloads
          jackett:
            - path: /config
              subPath: jackett/config
            - path: /downloads
              subPath: jackett/downloads
          radarr:
            - path: /config
              subPath: radarr/config
            - path: /downloads/complete
              subPath: transmission/downloads/complete
            - path: /movies
              subPath: movies
          jellyseerr:
            - path: /config
              subPath: jellyseerr/config
