jellyfin:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
      hosts:
      - host: jellyfin.khuedoan.com
        paths:
          - path: /
            pathType: Prefix
      tls:
      - secretName: jellyfin-tls-certificate
        hosts:
        - jellyfin.khuedoan.com
