app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/jellyfin/jellyfin
            tag: 10.8.13
  service:
    main:
      ports:
        http:
          port: 8096
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host jellyfin.khuedoan.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      globalMounts:
        - path: /config
    media:
      accessMode: ReadWriteOnce
      size: 20Gi
      globalMounts:
        - path: /media
