- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Wireguard
  apt:
    name: wireguard

- name: Generate Wireguard keypair
  shell: wg genkey | tee /etc/wireguard/privatekey | wg pubkey | tee /etc/wireguard/publickey
  args:
    creates: /etc/wireguard/privatekey

- name: Register private key
  slurp:
    src: /etc/wireguard/privatekey
  register: wireguard_private_key

- name: Register public key
  slurp:
    src: /etc/wireguard/publickey
  register: wireguard_public_key

- name: Generate wg0 config
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf

- name: Start Wireguard service
  service:
    name: wg-quick@wg0
    enabled: yes
    state: started
