---
- name: Install LXD
  package:
    name: lxd
    state: present

- name: Copy LXD preseed
  template:
    src: lxd_preseed.yml.j2
    dest: /tmp/lxd_preseed.yml

- name: Initialize LXD
  shell: "lxd init --preseed < /tmp/lxd_preseed.yml"

- name: Make LXD to be available over the network
  command: lxc config set core.https_address "[::]"

- name: Set password for new clients
  command: lxc config set core.trust_password "{{ lookup('env','LXD_PASSWORD') }}"

- name: Disable swap for Kubernetes
  command: swapoff -a

- name: Add the br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present
