- name: Start PXE server on the controller
  hosts: controller
  vars_prompt:
    - name: username
      prompt: Enter username for metal nodes
      private: no
    - name: password
      prompt: Enter password for metal nodes
  roles:
    - pxe-server

- name: Shutdown all nodes
  hosts: metal
  roles:
    - shutdown
  ignore_unreachable: yes

- name: Wake all nodes up
  hosts: metal
  gather_facts: no
  roles:
    - wake

- name: Provision
  hosts: metal
  roles:
    - tools
    - lxd
