- name: Start PXE server on the controller
  hosts: controller
  roles:
    - { role: pxe-server, tag: pxe-server }

- name: Shutdown all nodes
  hosts: homelab
  roles:
    - { role: shutdown, tag: shutdown }
  ignore_unreachable: yes

- name: Wake all nodes up
  hosts: homelab
  gather_facts: no
  roles:
    - { role: wake, tag: wake }
