- name: Install OS on empty nodes
  hosts: controller
  vars_prompt:
    - name: username
      prompt: Enter username for metal nodes
      private: no
    - name: password
      prompt: Enter password for metal nodes
  roles:
    - pxe-boot

- name: Provision
  hosts: metal
  vars_prompt:
    - name: lxd_password
      prompt: Enter password for LXD cluster
  roles:
    - snap
    - lxd
