- name: Install OS on empty nodes
  hosts: metal
  gather_facts: no
  tasks:
    - name: Unconditionally shut down the machine with all defaults
      community.general.shutdown:
        delay: 0
      ignore_unreachable: yes

    # TODO (optimize) Find a way to make sure the machines are shut down
    - name: Wait for the machine to shutdown
      wait_for:
        timeout: 30
      delegate_to: localhost
