---
- name: Add OpenNebula repository
  yum_repository:
    name: opennebula
    description: OpenNebula Community Edition
    baseurl: https://downloads.opennebula.io/repo/5.12/CentOS/8/$basearch
    gpgkey: https://downloads.opennebula.io/repo/repo.key
    gpgcheck: yes
    repo_gpgcheck: yes

- name: Install OpenNebula
  package:
    name: "{{ opennebula_packages }}"
    state: present

- name: Enable OpenNebula services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - opennebula
    - opennebula-sunstone
