---
- name: Add OpenNebula key
  apt_key:
    url: https://downloads.opennebula.io/repo/repo.key
    state: present

- name: Add OpenNebula repository
  apt_repository:
    repo: deb https://downloads.opennebula.io/repo/5.12/Ubuntu/18.04 stable opennebula
    filename: opennebula
    update_cache: yes
    state: present

- name: Install OpenNebula
  package:
    name: "{{ opennebula_packages }}"
    state: present

- name: Enable OpenNebula services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - opennebula
    - opennebula-sunstone
