trow:
  trow:
    domain: registry.khuedoan.com
    # user: user
    # password: password
    validation:
      enabled: false
      allowDocker: false
      allowKubernetes: true
      allowPrefixes: []
      allowImages: []
      disallowLocalPrefixes: []
      disallowLocalImages: []
      proxyDockerHub: false

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
    - host: &host registry.khuedoan.com
      paths:
        - "/"
    tls:
    - secretName: trow-tls-certificate
      hosts:
        - *host
