- name: Install LXD
  snap:
    name: lxd

- name: Init LXD on leader node
  command:
    cmd: /snap/bin/lxd init --preseed
    stdin: "{{ lookup('template', 'leader.yaml.j2') }}" 
    creates: /var/snap/lxd/common/lxd/server.crt
  when: inventory_hostname == groups['metal'][0]

- name: Get LXD server certificate
  slurp:
    # TODO change to /var/lib/lxd/server.crt after https://wiki.debian.org/LXD
    src: /var/snap/lxd/common/lxd/server.crt
  register: server_cert
  when: inventory_hostname == groups['metal'][0]

- name: Init LXD on member nodes
  command:
    cmd: /snap/bin/lxd init --preseed
    stdin: "{{ lookup('template', 'member.yaml.j2') }}" 
    creates: /var/snap/lxd/common/lxd/server.crt
  when: inventory_hostname != groups['metal'][0]
