# TODO (optimize) LXD node SELinux
- name: Disable SELinux
  selinux:
    state: disabled

# TODO (optimize) LXD node firewall
- name: Disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Enable LXD repository
  community.general.copr:
    name: ganto/lxc4
    state: enabled

- name: Install LXD packages
  dnf:
    name:
      - lxd
      - lxd-agent
      - edk2-ovmf
      - genisoimage
      - qemu-img
      - qemu-system-x86-core
      - qemu-char-spice
      - qemu-device-usb-redirect
      - qemu-device-display-virtio-vga
      - qemu-device-display-virtio-gpu

- name: Set subuid/subgid range for mapping container users/groups to host UIDs/GIDs
  lineinfile:
    path: "{{ item }}"
    line: "root:1000000:65536"
  loop:
    - /etc/subuid
    - /etc/subgid

- name: Enable LXD service
  service:
    name: lxd
    state: started
    enabled: yes

- name: Init LXD on leader node
  command:
    cmd: lxd init --preseed
    stdin: "{{ lookup('template', 'leader.yaml.j2') }}" 
    creates: /var/lib/lxd/cluster.crt
  when: inventory_hostname == groups['metal'][0]

- name: Get LXD server certificate
  slurp:
    src: /var/lib/lxd/cluster.crt
  register: server_cert
  when: inventory_hostname == groups['metal'][0]

- name: Init LXD on member nodes
  command:
    cmd: lxd init --preseed
    stdin: "{{ lookup('template', 'member.yaml.j2') }}" 
    creates: /var/lib/lxd/cluster.crt
  when: inventory_hostname != groups['metal'][0]

# TODO (optimize) Use template for tfvars
- name: Add LXD server to environment variables
  lineinfile:
    path: "{{ playbook_dir }}/../infra/terraform.tfvars"
    line: "lxd_address = \"{{ hostvars[groups['metal'][0]]['ansible_host'] }}\""
    create: yes
  delegate_to: localhost
  run_once: yes

- name: Add LXD password to environment variables
  lineinfile:
    path: "{{ playbook_dir }}/../infra/terraform.tfvars"
    line: "lxd_password = \"{{ lxd_password }}\""
    create: yes
  delegate_to: localhost
  run_once: yes
