gitea:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      external-dns.alpha.kubernetes.io/exclude: 'true'
    hosts:
      - host: git.khuedoan.com
        paths:
          - path: /
            pathType: Prefix
    tls:
    - secretName: gitea-tls-certificate
      hosts:
        - git.khuedoan.com
  gitea:
    config:
      server:
        LANDING_PAGE: explore
  persistence:
    storageClass: longhorn
  postgresql:
    persistence:
      storageClass: longhorn
