- name: Wait for etcd
  wait_for:
    port: 23799
    host: '{{ ansible_ssh_host }}'
  connection: local

- name: Generate Terraform backend config
  delegate_to: localhost
  template:
    src: backend.tfvars.j2
    dest: "{{ playbook_dir }}/../infra/backend.tfvars"
