- name: Create etcd container
  docker_container:
    name: etcd-tfstate
    image: bitnami/etcd
    restart_policy: always
    env:
      ALLOW_NONE_AUTHENTICATION: "yes"
    published_ports:
      - 2379:2379
    volumes:
      - tfstate:/bitnami/etcd/data
