- name: Install EPEL repository
  yum:
    name: epel-release

- name: Install snap
  yum:
    name: snapd

- name: Start snap service
  service:
    name: snapd.socket
    state: started
    enabled: yes

- name: Enable classic snap support
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: Get the latest snapd
  snap:
    name: core
