apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: global-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: global-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: {{ .Release.Namespace }}
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets-kubernetes-store
          namespace: {{ .Release.Namespace }}
