# TODO use redis and postgres when available
authelia:
  pod:
    kind: StatefulSet
  configMap:
    authentication_backend:
      ldap:
        enabled: false
      file:
        enabled: true
        password:
          algorithm: sha512
          iterations: 100000
    session:
      redis:
        enabled: false
    storage:
      local:
        enabled: true
      postgres:
        enabled: false
    notifier:
      filesystem:
        enabled: true
      smtp:
        enabled: false
