- name: Gather network facts
  ansible.builtin.setup:
    gather_subset:
      - network

- name: Create build directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ role_path }}/build"
    - "{{ role_path }}/files/images"
    - "{{ role_path }}/build/mnt"

- name: Copy configs
  copy:
    src: "{{ role_path }}/templates/"
    dest: "{{ role_path }}/build"

- name: Render DHCP config
  template:
    src: dhcp/dhcpd.conf.j2
    dest: "{{ role_path }}/build/dhcp/dhcpd.conf"

- name: Start ephemeral PXE server
  docker_compose:
    project_src: "{{ role_path }}/build"
    state: present
    restarted: yes
    build: yes
    recreate: always
