apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  destination:
    name: in-cluster
    namespace: kube-system
    server: ''
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 2.3.5
    chart: metallb
    helm:
      parameters:
        - name: 'configInline'
          value: |
            address-pools:
            - name: default
              protocol: layer2
              addresses:
              - 192.168.1.150-192.168.1.180 # TODO (optimize) Use metal values for MetalLB values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
