- hosts: all
  gather_facts: no
  tasks:
    - name: Wait for SSH connection
      wait_for_connection:
        delay: 10

- hosts: all
  become: yes
  tasks:
    - apt:
        update_cache: yes
  roles:
    - name: wireguard
