- name: Render configs and start PXE server
  include_tasks:
    file: server.yml
  run_once: yes
  when:
    - "'controller' in group_names"

- name: Wakes the nodes up and install OS on them
  include_tasks:
    file: wake.yml
  when:
    - "'metal' in group_names"
