# pip install kuberentes
- name: Bootstrap external secrets
  hosts: localhost
  vars_prompt:
    - name: cloudflare_email
      prompt: Enter Cloudflare email
      private: no
    - name: cloudflare_api_key
      prompt: Enter Cloudflare API Key (sensitive)
    - name: cloudflare_account_id
      prompt: Enter Cloudflare account ID
      private: no
    - name: b2_application_key_id
      prompt: Enter Backblaze application key ID
      private: no
    - name: b2_application_key
      prompt: Enter Backblaze application key (sensitive)
  tasks:
    - name: Ensure required namespaces exist
      kubernetes.core.k8s:
        name: "{{ item }}"
        api_version: v1
        kind: Namespace
        state: present
      loop:
        - tekton-pipelines
        - cert-manager
        - external-dns
        - cloudflared
    - name: Render environment file
      template:
        src: ./terraform.tfvars.j2
        dest: ./terraform.tfvars
