# pip install kuberentes
- name: Bootstrap external secrets
  hosts: localhost
  vars_prompt:
    - name: cloudflare_email
      prompt: Enter Cloudflare email
      private: no
    - name: cloudflare_api_key
      prompt: Enter Cloudflare API Key (sensitive)
    - name: cloudflare_account_id
      prompt: Enter Cloudflare account ID
      private: no
    - name: b2_application_key_id
      prompt: Enter Backblaze application key ID
      private: no
    - name: b2_application_key
      prompt: Enter Backblaze application key (sensitive)
  tasks:
    - name: Render environment file
      template:
        src: ./terraform.tfvars.j2
        dest: ./terraform.tfvars
    - name: Ensure required namespaces exist
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ item }}"
        state: present
      loop:
        - tekton-pipelines
        - cert-manager
        - external-dns
        - cloudflared
    - name: Add Terraform secrets to Tekton namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: terraform
            namespace: tekton-pipelines
          data:
            credentials.tfrc.json: "{{ lookup('file', '~/.terraform.d/credentials.tfrc.json') | b64encode }}"
            terraform.tfvars: "{{ lookup('file', './terraform.tfvars') | b64encode }}"
