# pip install kuberentes
- hosts: localhost
  tasks:
    - name: Inject Terraform secrets to Tekton namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: terraform-secrets
            namespace: tekton-pipelines
          data:
            credentials.tfrc.json: "{{ lookup('file', '~/.terraform.d/credentials.tfrc.json') | b64encode }}"
            terraform.tfvars: "{{ lookup('file', './terraform.tfvars') | b64encode }}"
