velero:
  configuration:
    provider: aws
  initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.3.0
    volumeMounts:
    - mountPath: /target
      name: plugins
