iso_url: "https://mirrors.nhanhoa.com/centos/8.3.2011/isos/x86_64/CentOS-8.3.2011-x86_64-dvd1.iso"

subnet: "192.168.1.0"
netmask: "255.255.255.0"
gateway: "192.168.1.1"
range_start: "192.168.1.11"
range_end: "192.168.1.99"
pxe_server: "192.168.1.21"
dns: "8.8.8.8"
network_device: "eno1"
disk: "sda"
ssh_public_key: "{{lookup('file', '~/.ssh/id_rsa.pub') }}"
